# Generated by Django 5.0.6 on 2024-06-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kometa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('comet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='kometa.comets')),
            ],
        ),
    ]
