# Generated by Django 5.0.6 on 2024-06-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kometa', '0002_specification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
