# Generated by Django 5.0.6 on 2024-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kometa', '0003_delete_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comets',
            name='prompt',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
