# Generated by Django 5.0.6 on 2024-06-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kometa', '0004_comets_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comets',
            old_name='prompt',
            new_name='myprompt',
        ),
    ]
