# Generated by Django 5.0.6 on 2024-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
