# Generated by Django 5.0.6 on 2024-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('magnitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
