# Generated by Django 5.0.6 on 2024-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_stars_delete_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
